from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List, Dict, Any

import torch
from torchvision import transforms as T
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

from .data.minneapple import CocoAppleDataset
from .models.detector import create_model


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Evaluate a detector on COCO-style dataset and report mAP (COCO)")
    p.add_argument("--dataset-root", type=str, required=True, help="Path to dataset root (COCO layout)")
    p.add_argument("--val-ann", type=str, default="annotations/instances_val.json")
    p.add_argument("--val-images", type=str, default="images/val")
    p.add_argument("--checkpoint", type=str, required=True, help="Path to model checkpoint (.pth)")
    p.add_argument("--results-json", type=str, default="coco_results.json", help="Where to save detections JSON")
    p.add_argument("--score-threshold", type=float, default=0.0, help="Score threshold for keeping detections (default keep all)")
    p.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    return p.parse_args()


def _to_coco_bbox(xyxy: torch.Tensor) -> List[float]:
    x1, y1, x2, y2 = xyxy.tolist()
    return [float(x1), float(y1), float(max(0.0, x2 - x1)), float(max(0.0, y2 - y1))]


def run_inference(ds: CocoAppleDataset, ckpt_path: Path, device: torch.device, score_thr: float = 0.0) -> List[Dict[str, Any]]:
    model = create_model(num_classes=2, pretrained=False)
    state = torch.load(ckpt_path, map_location=device)
    model.load_state_dict(state)
    model.to(device)
    model.eval()

    to_tensor = T.ToTensor()

    results: List[Dict[str, Any]] = []

    # Important: use actual COCO image ids from underlying CocoDetection (self.ids)
    assert hasattr(ds, "ids"), "Dataset must inherit from CocoDetection and expose 'ids'"

    with torch.no_grad():
        for idx in range(len(ds)):
            img_pil, _ = ds[idx]
            img = to_tensor(img_pil).to(device)
            outputs = model([img])[0]

            image_id = int(ds.ids[idx])  # COCO image id
            boxes = outputs.get("boxes", torch.empty((0, 4)))
            scores = outputs.get("scores", torch.empty((0,)))
            labels = outputs.get("labels", torch.empty((0,), dtype=torch.int64))

            for b, s, l in zip(boxes, scores, labels):
                if float(s) < score_thr:
                    continue
                coco_box = _to_coco_bbox(b.cpu())
                # Map class 1 to category_id=1 (apples)
                category_id = int(l)
                results.append({
                    "image_id": image_id,
                    "category_id": category_id,
                    "bbox": coco_box,
                    "score": float(s),
                })
    return results


def evaluate_coco(ann_path: Path, detections: List[Dict[str, Any]]):
    coco_gt = COCO(ann_path.as_posix())

    # Some COCO JSONs (including ones generated by quick converters) may omit optional
    # fields like 'info' or 'licenses'. pycocotools.loadRes expects to copy these keys
    # from the ground-truth dataset. Add sensible defaults if missing to avoid KeyError.
    ds = coco_gt.dataset
    if 'info' not in ds:
        ds['info'] = {}
    if 'licenses' not in ds:
        ds['licenses'] = []

    if len(detections) == 0:
        print("[evaluate_coco] Warning: No detections, skipping evaluation.")
        return None
    coco_dt = coco_gt.loadRes(detections)
    evaluator = COCOeval(coco_gt, coco_dt, iouType="bbox")
    evaluator.evaluate()
    evaluator.accumulate()
    evaluator.summarize()
    return evaluator


def main_cli():
    args = parse_args()

    root = Path(str(args.dataset_root).replace("\\", "/"))

    # Build dataset using relative paths so the dataset class joins with root once
    ds = CocoAppleDataset(root, args.val_ann, args.val_images)

    # For COCO evaluation and results saving, derive explicit paths here
    ann_path = root / args.val_ann
    device = torch.device(args.device)
    detections = run_inference(ds, Path(args.checkpoint), device=device, score_thr=float(args.score_threshold))

    results_path = Path(args.results_json)
    # If a relative path is provided, place it under the dataset root for convenience
    if not results_path.is_absolute():
        results_path = root / results_path
    results_path.parent.mkdir(parents=True, exist_ok=True)

    with open(results_path, "w", encoding="utf-8") as f:
        json.dump(detections, f)
    print(f"Saved detections to {results_path}")

    evaluate_coco(ann_path, detections)


if __name__ == "__main__":
    main_cli()
